### ISSUE TITLE
Generar un archivo de texto llamado "Python.txt" en el cual contenga la definicion de Python.

### ISSUE THREAD

**Issue by eliasgiannantonio** [eliasgiannantonio/ISPC-ProyectoInt#3]

**Comment by tuttiRoble** [comment]
¿Qué es Python?
Python es un lenguaje del tipo interpretado, multiparadigma: – Soporta orientación a objetos (oop).- Programación imperativa y funcional.- Es de tipado dinámico, multiplataforma y multipropósito.
